In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('./synthetic_healthcare_300k.csv')


df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Medication,Test Results,Date of Admission,Discharge Date
0,Allison Hill,69,Female,AB-,Obesity,Dr. Raymond Willis,Davis PLC Hospital,Cigna,43185.95,6656,Emergency,Metformin,Normal,2020-02-16 15:18:35.607718688,2020-03-04 15:18:35.607718688
1,Noah Rhodes,32,Female,AB-,Obesity,Dr. Hannah Thompson,Vaughn-Martin Hospital,Medicare,28234.22,9033,Urgent,Lipitor,Normal,2021-01-30 03:41:45.068350240,2021-01-31 03:41:45.068350240
2,Angie Henderson,89,Female,B+,Diabetes,Dr. Amber Velazquez,"Wade, Williams and Ferguson Hospital",Private,32884.72,8459,Elective,Lipitor,Inconclusive,2023-08-29 09:27:03.569411904,2023-09-12 09:27:03.569411904
3,Daniel Wagner,78,Female,O-,Cancer,Dr. Matthew Oconnor,Mata Ltd Hospital,Cigna,15581.19,9465,Elective,Ibuprofen,Inconclusive,2020-12-11 23:00:54.996183328,2021-01-09 23:00:54.996183328
4,Cristian Santos,38,Male,O-,Cancer,Dr. Alexandra Massey,Berry LLC Hospital,UnitedHealthcare,8545.10,4055,Urgent,Paracetamol,Inconclusive,2020-04-23 09:36:58.291394304,2020-05-22 09:36:58.291394304

In [4]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Name                300000 non-null  object
 1   Age                 300000 non-null  int64
 2   Gender              300000 non-null  object
 3   Blood Type          300000 non-null  object
 4   Medical Condition   300000 non-null  object
 5   Doctor              300000 non-null  object
 6   Hospital            300000 non-null  object
 7   Insurance Provider  300000 non-null  object
 8   Billing Amount      300000 non-null  float64
 9   Room Number         300000 non-null  int64
 10  Admission Type      300000 non-null  object
 11  Medication          300000 non-null  object
 12  Test Results        300000 non-null  object
 13  Date of Admission   300000 non-null  object
 14  Discharge Date      300000 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 34.3+ MB